import { StyleSheet } from 'react-native';
import { colors } from './colors';

export default StyleSheet.create({
  background: {
    flex: 1,
    resizeMode: 'cover',
  },
  container: {
    flexGrow: 1,
    paddingTop: 5,
    fontFamily: 'Open Sans',   
    paddingRight:20,
    paddingBottom: 40,
    
  },

   circleBackground: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header:{    
    top:30,
    right: 5,
    flexDirection: 'row',    
  },
  nav: {
    backgroundColor: '#00764f',
    padding: 10,  
    marginBottom: 30,
    marginRight:10, 
    width:'75%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  nav_disconnected:{
    backgroundColor: '#00764f',
    padding: 10,  
    marginBottom: 30,
    marginRight:10, 
    width:'100%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  status:{
    marginLeft:20,
    flexDirection: 'row',
     justifyContent: 'space-between',
     alignItems: 'center',
  },
  nav_bg: {
     position: 'absolute',
    borderWidth: 2,
    borderRadius:5,
    borderColor: 'rgb(0, 0, 0)',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
     opacity: 0.6,
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.whiteG,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 3,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#fcb1fb',
    textAlign: 'center',
    marginTop: 5,
    fontWeight: '500',
  },

   disconnectButton: {
    backgroundColor: colors.errorG,
    padding: 10,
    borderRadius: 5,
    marginBottom: 30,
    borderWidth: 2,
    width: '20%',
    justifyContent: 'center',
    borderColor: colors.secondaryG,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  disconnectButtonText: {
    color: colors.whiteG,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
  },
  statusCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  statusText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft:10,
    color: colors.whiteG,
  },
  deviceName: {
    fontWeight: 'bold',
    color: colors.accentG,
  },

   buttonsContainer: {
    marginLeft: '-4%',
    width:'90%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '6%',
  },
  circularButtonWrapper: {
    width: 200,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },

  circleImage: {
    width: '100%',
    height: '100%',
  },

  dividerLineL: {
    position: 'absolute',
    top: '50%',
    width: '80%',             
    left: '10%',
    right: 0,
    height: 5,              
    backgroundColor: '#1c1c1c', 
    opacity: 0.8,
  },

   dividerLineR: {
    position: 'absolute',
    left: '50%',
    height: '80%',            
    top: '10%',
    right: 0,
    width: 5,              
    backgroundColor: '#1c1c1c', 
    opacity: 0.8,
  },

  arrowTouchArea: {
    position: 'absolute',
    width: 80,              
    height: 80,             
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowIcon: {
    width: 50,
    height: 50,
    tintColor: colors.accentP,   
  },

  
  arrowUp: {
    top: 20,
  },
  arrowDown: {
    bottom: 20,
  },
  arrowLeft: {
    left: 20,
  },
  arrowRight: {
    right: 20,
  },


  speedContainer: {
    alignItems: 'center',
    position: 'relative',
  },
  speedLabel: {
    fontSize: 12,
    color: colors.textSecondaryG,
    letterSpacing: 1,
    marginBottom: 5,
  },
  speedValue: {
    fontSize: 40,
    fontWeight: 'bold',
    color: colors.whiteG,
    marginBottom: 15,
    position: 'absolute',
    top: '55%',
  },
  speedControls: {
    position: 'absolute',
    top: '80%',
    left:'43%',
    flexDirection: 'row',
    alignItems: 'center',
    width: '35%',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  circleButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  speedUpButton: {
    backgroundColor: colors.secondaryG,
  },
  speedDownButton: {
    backgroundColor: colors.secondaryG,
  },
  buttonIcon: {
    fontSize: 24,
    color: colors.whiteG,
    fontWeight: 'bold',
  },
  speedBarContainer: {
    flex: 1,
    height: 10,
    backgroundColor: colors.backgroundG,
    borderRadius: 5,
    marginHorizontal: 15,
    overflow: 'hidden',
  },
  speedBar: {
    height: '100%',
    backgroundColor: colors.accentP,
    borderRadius: 5,
    borderColor: colors.primaryG,
  },
  modeSelector: {
    backgroundColor: colors.secondaryDark,
    padding: 15,
    borderRadius: 30,
    marginVertical: 10,
    borderWidth: 2,
    borderColor: colors.secondaryG,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  modeSelectorText: {
    color: colors.whiteG,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
  },
  buttonControls: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 20,
    padding: 10,
    marginTop:15,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlButton: {
    padding: 18,
    borderRadius: 12,
    marginVertical: 8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  forwardButton: {
    backgroundColor: colors.secondaryG,
    borderWidth: 2,
    borderColor: colors.secondaryG,
    width: 80,
  },
  backwardButton: {
    backgroundColor: colors.secondaryG,
    borderWidth: 2,
    borderColor: colors.secondaryG,
     width: 80,
  },
  leftButtonO: {
    backgroundColor: colors.secondaryG,
    borderWidth: 2,
    borderColor: colors.secondaryG,
    flex: 1,
    marginRight: 10,
    marginLeft:25,
    width: 80,
  },
  rightButtonO: {
    backgroundColor: colors.secondaryG,
    borderWidth: 2,
    borderColor: colors.secondaryG,  
    flex: 1,
    marginLeft: 10,
    marginRight: 25,
    width: 80,
    
  },
  stopButton: {
    backgroundColor: colors.accentG,
    borderWidth: 2,
    borderColor: colors.secondaryG,
    width: 80,
  },
  controlButtonText: {
    color: colors.whiteG,
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  middleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  joystickContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 20,
    padding: 20,
    marginTop: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  joystickBackground: {
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: colors.primaryLightG,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 8,
    borderColor: colors.primaryG,
  },
  joystickText: {
    color: colors.whiteG,
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 20,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 2,
  },
  joystickPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primaryDarkG,
    borderWidth: 4,
    borderColor: colors.whiteG,
  },

  connectContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    marginTop: 50,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  connectTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.primaryDarkG,
    marginBottom: 10,
  },
  connectMessage: {
    fontSize: 16,
    color: colors.textSecondaryG,
    textAlign: 'center',
    marginBottom: 25,
  },
  connectButton: {
    backgroundColor: colors.primaryG,
    padding: 18,
    borderRadius: 30,
    width: '100%',
    borderWidth: 2,
    borderColor: colors.secondaryG,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  connectButtonText: {
    color: colors.whiteG,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
    fontSize: 16,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: colors.surfaceG,
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.primaryDarkG,
    textAlign: 'center',
    marginBottom: 20,
  },
  scanningContainer: {
    padding: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanningText: {
    marginTop: 15,
    color: colors.textSecondaryG,
  },
  devicesList: {
    maxHeight: 300,
  },
  deviceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.backgroundG,
  },
  deviceIcon: {
    backgroundColor: colors.primaryLightG,
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  deviceIconText: {
    fontSize: 24,
  },
  deviceInfo: {
    flex: 1,
  },
  deviceNameText: {
    fontSize: 16,
    fontWeight: '500',
    color: colors.textG,
  },
  deviceIdText: {
    fontSize: 12,
    color: colors.textSecondaryG,
    marginTop: 3,
  },
  modalButtons: {
    flexDirection: 'row',
    marginTop: 20,
  },
  scanAgainButton: {
    flex: 1,
    backgroundColor: colors.primaryLightG,
    padding: 15,
    borderRadius: 10,
    marginRight: 10,
  },
  scanAgainText: {
    color: colors.whiteG,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  closeModalButton: {
    flex: 1,
    backgroundColor: colors.errorG,
    padding: 15,
    borderRadius: 10,
  },
  closeModalText: {
    color: colors.whiteG,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  joystickSubtext: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 14,
    fontStyle: 'italic',
    marginBottom: 15,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 2,
  },
  scanningSubtext: {
    fontSize: 12,
    color: colors.textSecondaryG,
    marginTop: 5,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  deviceLastSeen: {
    fontSize: 10,
    color: colors.textSecondaryG,
    marginTop: 2,
    fontStyle: 'italic',
  },
  noDevicesContainer: {
    padding: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noDevicesText: {
    fontSize: 16,
    color: colors.textSecondaryG,
    textAlign: 'center',
    marginBottom: 10,
    fontWeight: '500',
  },
  noDevicesSubtext: {
    fontSize: 12,
    color: colors.textSecondaryG,
    textAlign: 'center',
    lineHeight: 18,
    fontStyle: 'italic',
  },
  bluetoothStatus: {
    marginTop: 10,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 15,
    paddingRight: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 20,
    alignSelf: 'center',
  },
  bluetoothStatusText: {
    color: colors.whiteG,
    fontWeight: '500',
    fontSize: 14,
  },
/* scrollContainer: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingBottom: 40,
  }, */
  bth_icon: {
    width: 18,
    height: 18,
    tintColor: '#FFFFFF',
  },
  icon: {
    width: 32,
    height: 32,
    tintColor: '#FFFFFF', 
  },
});